language: node_js
node_js:
  - "8"
script:
 - echo "Deploying!!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project fir-hostingwithtravisci --token $FIREBASE_TOKEN